### ISSUE TITLE
Update to Current Version of NIEM

### ISSUE THREAD

**Issue by pleework** [NIEM/Template-IEPD#3]
Can this template be updated to the most current version of NIEM?  As of the time of submitting/opening this issue, I believe NIEM is currently at version 4.1 (https://www.niem.gov/techhub/niem-model/current-release)

**Comment by DonClysdale** [comment]
I created issue to move model package description schema into niem-core and at current version. https://github.com/NIEM/NIEM-Releases/issues/46

**Comment by cdmgtri** [comment]
Thanks for the feedback!  We've updated the template to use NIEM 4.0 in the extension schema and sample instance.

The MPD Specification is still at version 3.0 and uses a NIEM 3.0 subset for the mpd-catalog file.  This is something we can't update in the template until the next version of the MPD specification is published.  

The NIEM Technical Architecture Committee (NTAC) is working on updating this so that a 5.0 MPD specification can be published along with the NIEM 5.0 release next year.

I'm closing out this issue since this is as updated as we can get it for now.  Don's issue re adding MPD spec components to NIEM Core is still currently open in the NIEM Releases repo and will be tracked there.

Thanks again!
